name: Build and push

on: [push]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up docker image
        id: setup
        run: |
          if [[ $GITHUB_REF =~ ^refs/tags/ ]]; then
            TAG=$(echo ${GITHUB_REF##*/})
          else
            TAG=$(echo ${GITHUB_SHA::7})
          fi
          if [[ $GITHUB_ACTOR =~ nektos/act ]]; then
            CONTEXT=.
          else
            CONTEXT={{defaultContext}}
          fi
          IMAGE=${{ secrets.DOCKERHUB_REPOSITORY }}
          echo ::set-output name=tagged_image::${IMAGE}:${TAG}
          echo ::set-output name=tag::${TAG}
          echo ::set-output name=context::${CONTEXT}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
            driver-opts: |
              env.http_proxy=${{ env.http_proxy }}
              env.https_proxy=${{ env.http_proxy }}

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ steps.setup.outputs.tagged_image }}
          context: ${{ steps.setup.outputs.context }}
          build-args: |
            http_proxy=${{ env.http_proxy }}
            https_proxy=${{ env.https_proxy }}
